language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andr095/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andr095/react-test npm run test -- --coverage

after_success:
  - docker build -t andr095/demo-client ./client
  - docker build -t andr095/demo-nginx ./nginx
  - docker build -t andr095/demo-api ./api
  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker hub
  - docker push andr095/demo-client
  - docker push andr095/demo-nginx
  - docker push andr095/demo-api

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "python-demo"
  env: "Pythondemo-env"
  bucket_name: "elasticbeanstalk-us-east-1-414579692089"
  bucket_path: "python-demo"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"