version: '3.8'

services:
  api:
    image: andr095/demo-api
    mem_limit: 128m
    hostname: api
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=production
      - SECRET_KEY=$SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
  nginx:
    image: andr095/demo-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  client:
    image: andr095/demo-client
    hostname: client
    mem_limit: 128m
