version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    # entrypoint: ['/usr/app/entrypoint.sh']
    volumes:
      - './api:/usr/app'
    ports:
      - 3050:5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=production
      - SECRET_KEY=$SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
    depends_on:
      - api-db
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
  api-db:
    build:
      context: ./api/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD==$POSTGRES_PASSWORD
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
      - REACT_APP_VERSION=$npm_package_version
      - REACT_APP_API_URL=$REACT_APP_API_URL
